//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rastreabilidade.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BIC.Strings.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Putz! .
        /// </summary>
        public static string FAIL {
            get {
                return ResourceManager.GetString("FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você precisa informar pelo menos o nome do módulo, mané!.
        /// </summary>
        public static string FAIL_EmptyModule {
            get {
                return ResourceManager.GetString("FAIL_EmptyModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você precisa informar pelo menos o nome da tabela, mané!.
        /// </summary>
        public static string FAIL_EmptyTable {
            get {
                return ResourceManager.GetString("FAIL_EmptyTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você precisa informar pelo menos o nome do caso de uso, mané!.
        /// </summary>
        public static string FAIL_EmptyUseCase {
            get {
                return ResourceManager.GetString("FAIL_EmptyUseCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuck yeah: .
        /// </summary>
        public static string SUCCESS {
            get {
                return ResourceManager.GetString("SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O módulo &apos;{0}&apos; foi deletado com sucesso \o/ !.
        /// </summary>
        public static string SUCCESS_ModuleDeleted {
            get {
                return ResourceManager.GetString("SUCCESS_ModuleDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O módulo &apos;{0}&apos; foi salvo com sucesso \o/ !.
        /// </summary>
        public static string SUCCESS_ModuleSaved {
            get {
                return ResourceManager.GetString("SUCCESS_ModuleSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A tabela &apos;{0}&apos; foi deletado com sucesso \o/ !.
        /// </summary>
        public static string SUCCESS_TableDeleted {
            get {
                return ResourceManager.GetString("SUCCESS_TableDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A tabela &apos;{0}&apos; foi salva com sucesso \o/ !.
        /// </summary>
        public static string SUCCESS_TableSaved {
            get {
                return ResourceManager.GetString("SUCCESS_TableSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O caso de uso &apos;{0}&apos; foi deletado com sucesso \o/ !.
        /// </summary>
        public static string SUCCESS_UseCaseDeleted {
            get {
                return ResourceManager.GetString("SUCCESS_UseCaseDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O caso de uso &apos;{0}&apos; foi salvo com sucesso \o/ !.
        /// </summary>
        public static string SUCCESS_UseCaseSaved {
            get {
                return ResourceManager.GetString("SUCCESS_UseCaseSaved", resourceCulture);
            }
        }
    }
}
